# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15wDvlbbacT1H6ICkDC_cJ4dKiGtfHgoS
"""

import pandas as pd
baza= {
    "FISH":[ "Abduhakimov Xursandbek", "Rahimova Guli", "Adhamova Kumush", "Aliyev Abror", "Karimov Islom", "Athamova Zebo", "Shukurov Nodir", "Salimova Sabina", "Anvarov Asilbek", "Akbarova Rano" ],
    "Yoshi":[ "19", "13", "17", "28", "32", "15", "10", "58", "9", "25" ],
    "Maktabi":[" 52", "27", "53", "52", "17", "1", "1", "18", "2", "26"],
    "Jinsi":["o'g'il bola", "qiz bola", "qiz bola", "o'g'il bola", "o'g'il bola", "qiz bola", "o'g'il bola", "qiz bola", "o'g'il bola", "qiz bola" ],
    "Manzili":[ "Andijon", "Namangan", "Buxoro", "Andijon", "Qoqon", "Andijon", "Toshkent", "Namangan", "Samarqand", "Jizzax" ]
}
db=pd.DataFrame(baza)
print (db)

filtr=db[db['Jinsi']=="qiz bola"]
print (filtr)

filtr=db[(db['Jinsi']=="qiz bola")&(db['Yoshi']=="25")]
print (filtr)